from app.models.categoria_tecnologia import CategoriaTecnologia
from app.models.dependencia_modulo import DependenciaModulo
from app.models.modulo import Modulo
from app.models.perfil_tecnologia import PerfilTecnologia
from app.models.perfil_usuario import PerfilUsuario
from app.models.progreso import Progreso
from app.models.recurso import Recurso
from app.models.recurso_progreso import RecursoProgreso
from app.models.ruta_aprendizaje import RutaAprendizaje
from app.models.usuario import Usuario
